INSERT INTO categorie VALUES (1, 'Animaux');
INSERT INTO categorie VALUES (2, 'Repas');
INSERT INTO categorie VALUES (3, 'Monuments');
INSERT INTO photo VALUES (1, 'DSC00011.jpg', 'Une perruche en cage', 1);
INSERT INTO photo VALUES (5, 'DSC01040.jpg', 'Un plateau télé', 2);
INSERT INTO photo VALUES (2, 'DSC01212.jpg', 'Un chien en laisse', 1);
INSERT INTO photo VALUES (3, 'DSC01422.jpg', 'Un canard dans l''eau', 1);
INSERT INTO photo VALUES (4, 'DSC01446.jpg', 'Une chèvre dans un pré', 1);
INSERT INTO photo VALUES (6, 'DSC01280.jpg', 'Quelque chose de sculpté', 3);
INSERT INTO photo VALUES (7, 'DSC01436.jpg', 'Un monument lointain', 3);
INSERT INTO photo VALUES (8, 'DSC01464.jpg', 'Un monument très très loin', 3);
INSERT INTO photo VALUES (9, 'DSC02764.jpg', 'Un monument vu d''en bas', 3);
